driver:
  name: vagrant

provisioner:
  name: chef_zero
  retry_on_exit_code:
    - 213
  max_retries: 1
  wait_for_retry: 1
  client_rb:
    exit_status: :enabled
    client_fork: false

verifier:
  name: inspec

platforms:
  - name: centos-6.8
  - name: centos-7.3
  - name: debian-7.11
  - name: debian-8.6
  - name: fedora-25
  - name: freebsd-9.3
  - name: freebsd-10.3
  - name: opensuse-leap-42.2
  - name: sles-12-sp1
    driver:
      box: chef/sles-12-sp1-x86_64 # private box
  - name: solaris-10.11
    driver:
      box: chef/solaris-10.11 # private box
  - name: solaris-11.3
    driver:
      box: chef/solaris-11.3 # private box
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: windows-2008r2
    driver:
      box: chef/windows-server-2008r2-standard # private box
  - name: windows-2012r2
    driver:
      box: chef/windows-server-2012r2-standard # private box

suites:

- name: client_upgrade
  driver:
    require_chef_omnibus: '12.15.19'
  run_list:
    - recipe[chef-client::client_upgrade]
- name: service_bsd
  run_list:
  - recipe[chef-client::config]
  - recipe[chef-client::bsd_service]
  includes: ["freebsd-9.3", "freebsd-10.3"]

- name: service_init
  run_list:
  - recipe[chef-client::config]
  - recipe[chef-client::init_service]
  includes: ["centos-5.11", "centos-6.8", "debian-7.11", "sles-12-sp1"]

- name: service_runit
  run_list:
  - recipe[runit]
  - recipe[chef-client::runit_service]
  includes: ["centos-5.11", "centos-6.8", "debian-7.11"]

- name: service_systemd
  run_list:
  - recipe[chef-client::systemd_service]
  includes: ["centos-7.3", "debian-8.6", "fedora-25", "ubuntu-16.04", "opensuse-leap-42.2"]

- name: service_upstart
  run_list:
  - recipe[chef-client::upstart_service]
  includes: ["ubuntu-14.04"]

- name: service_smf
  run_list:
  - recipe[chef-client::smf_service]
  includes: ["solaris-11.3", "solaris-10.11"]

- name: cron
  run_list:
  - recipe[cron::default]
  - recipe[chef-client::cron]
  excludes: ["windows-2008r2", "windows-2012r2"]

- name: config
  run_list:
  - recipe[chef-client::config]
  attributes:
    ohai:
      disabled_plugins:
        - Mdadm
      plugin_path: "/tmp/kitchen/ohai/plugins"

- name: delete_validation
  run_list:
  - recipe[chef-client::delete_validation]

# Test that the we can use the cron_d directory
- name: cook-use_cron_d
  run_list:
  - recipe[cron::default]
  - recipe[chef-client::cron]
  attributes:
    chef_client:
      cron:
        use_cron_d: true
  excludes: ["windows-2008r2", "windows-2012r2"]

# Testing when we are using chef-client on a Chef Server
- name: server
  run_list:
  - recipe[chef-server]
  - recipe[chef-client::config]
  - recipe[chef-client::service]
  includes: ["ubuntu-14.04", "centos-6.8", "centos-7.3"]

- name: task
  run_list:
    - recipe[chef-client::task]
  includes: ["windows-2008r2", "windows-2012r2"]
