driver:
  name: dokken
  chef_image: chef/chef
  chef_version: current
  privileged: true # because Docker and SystemD/Upstart

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec

platforms:
- name: debian-7
  driver:
    image: debian:7
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install lsb-release procps -y

- name: debian-8
  driver:
    image: debian:8
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install lsb-release -y

- name: centos-6
  driver:
    image: centos:6
    platform: rhel
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN yum -y install which initscripts

- name: centos-7
  driver:
    image: centos:7
    platform: rhel
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
      - RUN yum -y install lsof which systemd-sysv initscripts

- name: fedora-latest
  driver:
    image: fedora:latest
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
      - RUN dnf -y install yum which systemd-sysv initscripts

- name: ubuntu-14.04
  driver:
    image: ubuntu-upstart:14.04
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: ubuntu-16.04
  driver:
    image: ubuntu:16.04
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: opensuse-leap
  driver:
    image: opensuse:leap
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN zypper --non-interactive install aaa_base perl-Getopt-Long-Descriptive which

suites:
- name: service_init
  run_list:
  - recipe[chef-client::config]
  - recipe[chef-client::init_service]
  includes: ["debian-7", "centos-6"]

- name: service_runit
  run_list:
  - recipe[runit]
  - recipe[chef-client::runit_service]
  includes: ["debian-7", "centos-6"]

- name: service_systemd
  run_list:
  - recipe[chef-client::systemd_service]
  includes: ["centos-7", "debian-8", "opensuse-leap", "fedora-latest", "ubuntu-16.04"]

- name: service_upstart
  run_list:
  - recipe[chef-client::upstart_service]
  includes: ["ubuntu-14.04"]

- name: cron
  run_list:
  - recipe[cron::default]
  - recipe[chef-client::cron]

- name: config
  run_list:
  - recipe[chef-client::config]

- name: delete_validation
  run_list:
  - recipe[chef-client::delete_validation]
