---
driver_config:
  digitalocean_client_id: <%= ENV['DIGITAL_OCEAN_CLIENT_ID'] %>
  digitalocean_api_key: <%= ENV['DIGITAL_OCEAN_API_KEY'] %>
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %> 
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  availability_zone: <%= ENV['AWS_AVAILABILITY_ZONE'] %>

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
- name: centos-5.8
  driver_plugin: digital_ocean
  driver_config:
    size: 1gb
    image: centos-5-8-x64
    region: <%= ENV['DIGITAL_OCEAN_REGION'] %>

- name: centos-6.5
  driver_plugin: digital_ocean
  driver_config:
    size: 1gb
    image: centos-6-5-x64
    region: <%= ENV['DIGITAL_OCEAN_REGION'] %>

- name: centos-7.0
  driver_plugin: digital_ocean
  driver_config:
    size: 1gb
    image: centos-7-0-x64
    region: <%= ENV['DIGITAL_OCEAN_REGION'] %>

- name: amazon-2013.09
  driver_plugin: ec2
  driver_config:
    image_id: ami-e9a18d80
    username: ec2-user
    ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
    flavor_id: t2.small

- name: amazon-2014.03
  driver_plugin: ec2
  driver_config:
    image_id: ami-76817c1e
    username: ec2-user
    ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
    flavor_id: t2.small

- name: amazon-2014.09
  driver_plugin: ec2
  driver_config:
    image_id: ami-fccc6d94
    username: ec2-user
    ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
    flavor_id: t2.small

- name: suse-11.3
  driver_plugin: ec2
  driver_config:
    image_id: ami-96b117fe
    username: root
    ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
    flavor_id: t2.small

# UTF-8 is not a friend
#- name: fedora-19
#  driver_plugin: digital_ocean
#  driver_config:
#    size: 1gb
#    image: fedora-19-x64
#    region: <%= ENV['DIGITAL_OCEAN_REGION'] %>

- name: fedora-20
  driver_plugin: digital_ocean
  driver_config:
    size: 1gb
    image: fedora-20-x64
    region: <%= ENV['DIGITAL_OCEAN_REGION'] %>

- name: debian-7.0
  driver_plugin: digital_ocean
  driver_config:
    size: 1gb
    image: debian-7-0-x64
    region: <%= ENV['DIGITAL_OCEAN_REGION'] %>

- name: ubuntu-10.04
  driver_plugin: digital_ocean
  driver_config:
    size: 1gb
    image: ubuntu-10-04-x64
    region: <%= ENV['DIGITAL_OCEAN_REGION'] %>

- name: ubuntu-12.04
  driver_plugin: digital_ocean
  driver_config:
    size: 1gb
    image: ubuntu-12-04-x64
    region: <%= ENV['DIGITAL_OCEAN_REGION'] %>

- name: ubuntu-14.04
  driver_plugin: digital_ocean
  driver_config:
    size: 1gb
    image: ubuntu-14-04-x64
    region: <%= ENV['DIGITAL_OCEAN_REGION'] %>

suites:

- name: default
  run_list:
  - recipe[chef-client::config]
  - recipe[chef-client]
  attributes: {}

- name: service_init
  run_list:
  - recipe[chef-client::config]
  - recipe[chef-client::init_service]
  attributes: {}
  excludes: ["centos-7.0", "fedora-20"]

- name: service_runit
  run_list:
  - recipe[runit]
  - recipe[chef-client::runit_service]
  attributes: {}

- name: service_systemd
  run_list:
  - recipe[chef-client::systemd_service]
  attributes: {}
  includes: ["centos-7.0", "fedora-20"]

- name: service_upstart
  run_list:
  - recipe[chef-client::upstart_service]
  includes: ["ubuntu-10.04", "ubuntu-12.04", "ubuntu-14.04"]
  attributes: {}

- name: cron
  run_list:
  - recipe[chef-client::cron]
  attributes: {}

- name: delete_validation
  run_list:
  - recipe[chef-client::delete_validation]
  attributes: {}

# Test that the we can use the cron_d directory
- name: cook-use_cron_d
  run_list:
  - recipe[chef-client::cron]
  attributes:
    chef_client:
      cron:
        use_cron_d: true

# Test that the running process includes command-line "daemon" options
- name: cook-1951
  run_list:
  - recipe[chef-client::config]
  - recipe[chef-client::service]
  attributes:
    chef_client:
      init_style: "init"
      daemon_options: ["-E cook-1951"]
