driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-5.11
  - name: centos-6.6
  - name: centos-7.0
  - name: debian-7.7
  - name: fedora-20
  - name: fedora-21
  - name: freebsd-9.3
  - name: freebsd-10.1
  - name: ubuntu-10.04
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:

- name: service_bsd
  run_list:
  - recipe[chef-client::config]
  - recipe[chef-client::bsd_service]
  attributes: {}
  includes: ["freebsd-9.3", "freebsd-10.1"]

- name: service_init
  run_list:
  - recipe[chef-client::config]
  - recipe[chef-client::init_service]
  attributes: {}
  excludes: ["centos-7.0", "fedora-20", "fedora-21"]

- name: service_runit
  run_list:
  - recipe[runit]
  - recipe[chef-client::runit_service]
  attributes: {}

- name: service_systemd
  run_list:
  - recipe[chef-client::systemd_service]
  attributes: {}
  includes: ["centos-7.0", "fedora-20", "fedora-21"]

- name: service_upstart
  run_list:
  - recipe[chef-client::upstart_service]
  includes: ["ubuntu-10.04", "ubuntu-12.04", "ubuntu-14.04"]
  attributes: {}

- name: cron
  run_list:
  - recipe[chef-client::cron]
  attributes: {}

- name: config
  run_list:
  - recipe[chef-client::config]
  attributes: {}

- name: delete_validation
  run_list:
  - recipe[chef-client::delete_validation]
  attributes: {}

# Test that the we can use the cron_d directory
- name: cook-use_cron_d
  run_list:
  - recipe[chef-client::cron]
  attributes:
    chef_client:
      cron:
        use_cron_d: true

# Test that the running process includes command-line "daemon" options
- name: cook-1951
  run_list:
  - recipe[chef-client::config]
  - recipe[chef-client::service]
  attributes:
    chef_client:
      init_style: "init"
      daemon_options: ["-E cook-1951"]
