---
driver_plugin: vagrant
driver_plugin: digitalocean
driver_config:
  digitalocean_client_id: <%= ENV['DIGITAL_OCEAN_CLIENT_ID'] %>
  digitalocean_api_key: <%= ENV['DIGITAL_OCEAN_API_KEY'] %>
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %> 
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  ssh_key: <%= ENV['AWS_PRIVATE_KEY_PATH'] %>
  rackspace_username: <%= ENV['RACKSPACE_USERNAME'] %>
  rackspace_api_key: <%= ENV['RACKSPACE_API_KEY'] %>
  require_chef_omnibus: latest

platforms:
- name: centos-5.8
  driver_plugin: digitalocean
  driver_config:
    image_id: 1601
    flavor_id: 63
    region_id: 1
    ssh_key_ids: <%= ENV['DIGITAL_OCEAN_SSH_KEY_IDS'] %>

- name: centos-6.4
  driver_plugin: digitalocean
  driver_config:
    image_id: 562354
    flavor_id: 63
    region_id: 1
    ssh_key_ids: <%= ENV['DIGITAL_OCEAN_SSH_KEY_IDS'] %>

- name: amazon-2013.09
  driver_plugin: ec2
  driver_config:
    image_id: ami-3be4bc52
    username: ec2-user

- name: fedora-19
  driver_plugin: digitalocean
  driver_config:
    image_id: 696598
    flavor_id: 63
    region_id: 1
    ssh_key_ids: <%= ENV['DIGITAL_OCEAN_SSH_KEY_IDS'] %>

- name: ubuntu-1004
  driver_plugin: digitalocean
  driver_config:
    image_id: 14097
    flavor_id: 63
    region_id: 1
    ssh_key_ids: <%= ENV['DIGITAL_OCEAN_SSH_KEY_IDS'] %>
  run_list:
  - recipe[apt]

- name: ubuntu-1204
  driver_plugin: digitalocean
  driver_config:
    image_id: 1505447
    flavor_id: 63
    region_id: 1
    ssh_key_ids: <%= ENV['DIGITAL_OCEAN_SSH_KEY_IDS'] %>
  run_list:
  - recipe[apt]

- name: ubuntu-1310
  driver_plugin: digitalocean
  driver_config:
    image_id: 1505699
    flavor_id: 63
    region_id: 1
    ssh_key_ids: <%= ENV['DIGITAL_OCEAN_SSH_KEY_IDS'] %>
  run_list:
  - recipe[apt]

suites:
# This suite tests that the configuration is applied correctly (via attributes)
- name: config
  run_list:
  - recipe[minitest-handler]
  - recipe[chef-client_test::config]
  - recipe[chef-client::config]
  attributes:
    chef_client:
      load_gems:
        chef-handler-updated-resources:
          require_name: "chef/handler/updated_resources"
      config:
        log_level: ":debug"
        ssl_verify_mode: ":verify_peer"
        start_handlers: [{class: "SimpleReport::UpdatedResources", arguments: []}]
        report_handlers: [{class: "SimpleReport::UpdatedResources", arguments: []}]
        exception_handlers: [{class: "SimpleReport::UpdatedResources", arguments: []}]
    ohai:
      disabled_plugins: ["passwd"]

- name: service_init
  run_list:
  - recipe[minitest-handler]
  - recipe[chef-client::config]
  - recipe[chef-client_test::service_init]
  - recipe[chef-client::init_service]
  attributes: {}

- name: service_runit
  run_list:
  - recipe[minitest-handler]
  - recipe[runit]
  - recipe[chef-client_test::service_runit]
  - recipe[chef-client::runit_service]
  attributes: {}

- name: service_upstart
  run_list:
  - recipe[minitest-handler]
  - recipe[chef-client_test::service_upstart]
  - recipe[chef-client::upstart_service]
  excludes: ["centos-5.9"]
  attributes: {}

- name: cron
  run_list:
  - recipe[minitest-handler]
  - recipe[chef-client::cron]
  attributes: {}

- name: delete_validation
  run_list:
  - recipe[chef-client::delete_validation]
  attributes: {}

# Probably needs to be moved up to config and tested there
- name: cook-2092
  run_list:
  - recipe[minitest-handler]
  - recipe[chef-client_test::cook-2092]
  - recipe[chef-client::config]
  attributes:
    chef_client:
      log_file: "client.log"

# Tests that the root user is set correctly for the cron recipe.
- name: cook-2169-root
  run_list:
  - recipe[minitest-handler]
  - recipe[chef-client_test::cook-2169-root]
  - recipe[chef-client::cron]
  attributes: {}

# Tests that the "chef server" user is set correctly with the cron recipe.
- name: cook-2169-chef
  run_list:
  - recipe[minitest-handler]
  - recipe[chef-client_test::cook-2169-chef]
  - recipe[chef-client::cron]
  attributes: {}

# Test that the environment variables are rendered correctly
- name: cook-2086
  run_list:
  - recipe[minitest-handler]
  - recipe[chef-client_test::cook-2086]
  - recipe[chef-client::cron]
  attributes:
    chef_client:
      cron:
        environment_variables: "FOO=BAR"

# Test that the we can use the cron_d directory
- name: cook-use_cron_d
  run_list:
  - recipe[minitest-handler]
  - recipe[chef-client::cron]
  attributes:
    chef_client:
      cron:
        use_cron_d: true

# No longer necessary w/ COOK-2856
# - name: cook-2317
#   run_list:
#   - recipe[minitest-handler]
#   - recipe[chef-client::config]
#   - recipe[chef-client_test::cook-2317]
#   attributes:
#     ohai:
#       disabled_plugins: ["passwd"]

# Test that the running process includes command-line "daemon" options
- name: cook-1951
  run_list:
  - recipe[minitest-handler]
  - recipe[chef-client::config]
  - recipe[chef-client::service]
  - recipe[chef-client_test::cook-1951]
  attributes:
    chef_client:
      init_style: "init"
      daemon_options: ["-E cook-1951"]
