driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-5.11
  - name: centos-6.8
  - name: centos-7.2
  - name: debian-7.11
  - name: debian-8.5
  - name: fedora-24
  - name: freebsd-9.3
  - name: freebsd-10.3
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: opensuse-13.2
  - name: windows-2008r2
    driver_config:
      box: chef/windows-server-2008r2-standard # private box
  - name: windows-2012r2
    driver_config:
      box: chef/windows-server-2012r2-standard # private box

suites:

- name: service_bsd
  run_list:
  - recipe[chef-client::config]
  - recipe[chef-client::bsd_service]
  includes: ["freebsd-9.3", "freebsd-10.3"]

- name: service_init
  run_list:
  - recipe[chef-client::config]
  - recipe[chef-client::init_service]
  includes: ["centos-5.11", "centos-6.7", "debian-7.11"]

- name: service_runit
  run_list:
  - recipe[runit]
  - recipe[chef-client::runit_service]
  includes: ["centos-5.11", "centos-6.7", "debian-7.11"]

- name: service_systemd
  run_list:
  - recipe[chef-client::systemd_service]
  includes: ["centos-7.2", "debian-8.5", "fedora-23", "ubuntu-16.04", "opensuse-13.2"]

- name: service_upstart
  run_list:
  - recipe[chef-client::upstart_service]
  includes: ["ubuntu-12.04", "ubuntu-14.04"]

- name: cron
  run_list:
  - recipe[cron::default]
  - recipe[chef-client::cron]
  excludes: ["windows-2008r2", "windows-2012r2"]

- name: config
  run_list:
  - recipe[chef-client::config]
  attributes:
    ohai:
      disabled_plugins:
        - Mdadm

- name: delete_validation
  run_list:
  - recipe[chef-client::delete_validation]

# Test that the we can use the cron_d directory
- name: cook-use_cron_d
  run_list:
  - recipe[cron::default]
  - recipe[chef-client::cron]
  attributes:
    chef_client:
      cron:
        use_cron_d: true
  excludes: ["windows-2008r2", "windows-2012r2"]

# Test that the running process includes command-line "daemon" options
- name: cook-1951
  run_list:
  - recipe[chef-client::config]
  - recipe[chef-client::service]
  attributes:
    chef_client:
      init_style: "init"
      daemon_options: ["-E cook-1951"]
  excludes: ["freebsd-9.3", "freebsd-10.3", "windows-2008r2", "windows-2012r2"]

# Testing when we are using chef-client on a Chef Server (12+ only)
- name: server
  run_list:
  - recipe[chef-server]
  - recipe[chef-client::config]
  - recipe[chef-client::service]
  includes: ["ubuntu-12.04", "ubuntu-14.04", "centos-6.7", "centos-7.2"]

- name: task
  run_list:
    - recipe[chef-client::task]
  includes: ["windows-2008r2", "windows-2012r2"]
