driver:
  name: vagrant
  customize:
    memory: 1024
    cpus: 2

provisioner:
  name: chef_zero

platforms:
  - name: centos-5.11
  - name: centos-6.7
  - name: centos-7.2
  - name: debian-7.9
  - name: debian-8.2
  - name: fedora-22
  - name: fedora-23
  - name: freebsd-9.3
  - name: freebsd-10.2
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: ubuntu-14.04-chef-11
    driver_config:
      box: opscode-ubuntu-14.04
    provisioner:
      require_chef_omnibus: 11.18.6
  - name: ubuntu-15.04

suites:

- name: service_bsd
  run_list:
  - recipe[chef-client::config]
  - recipe[chef-client::bsd_service]
  includes: ["freebsd-9.3", "freebsd-10.2"]

- name: service_init
  run_list:
  - recipe[chef-client::config]
  - recipe[chef-client::init_service]
  excludes: ["centos-7.2", "debian-8.2", "fedora-22", "fedora-23", "freebsd-9.3", "freebsd-10.2"]

- name: service_runit
  run_list:
  - recipe[runit]
  - recipe[chef-client::runit_service]
  includes: ["ubuntu-12.04", "ubuntu-14.04", "debian-7.9", "debian-8.2"]

- name: service_systemd
  run_list:
  - recipe[chef-client::systemd_service]
  includes: ["centos-7.2", "debian-8.2", "fedora-22", "fedora-23", "ubuntu-15.04"]

- name: service_upstart
  run_list:
  - recipe[chef-client::upstart_service]
  includes: ["ubuntu-12.04", "ubuntu-14.04"]

- name: cron
  run_list:
  - recipe[cron::default]
  - recipe[chef-client::cron]

- name: config
  run_list:
  - recipe[chef-client::config]

- name: delete_validation
  run_list:
  - recipe[chef-client::delete_validation]

# Test that the we can use the cron_d directory
- name: cook-use_cron_d
  run_list:
  - recipe[cron::default]
  - recipe[chef-client::cron]
  attributes:
    chef_client:
      cron:
        use_cron_d: true

# Test that the running process includes command-line "daemon" options
- name: cook-1951
  run_list:
  - recipe[chef-client::config]
  - recipe[chef-client::service]
  attributes:
    chef_client:
      init_style: "init"
      daemon_options: ["-E cook-1951"]
  excludes: ["freebsd-9.3", "freebsd-10.2"]

# Testing when we are using chef-client on a Chef Server (12+ only)
- name: server
  run_list:
  - recipe[chef-server]
  - recipe[chef-client::config]
  - recipe[chef-client::service]
