name              "chef-client"
maintainer        "John Dewey"
maintainer_email  "john@dewey.ws"
license           "Apache 2.0"
description       "This cookbook is used with test-kitchen to test the parent, chef-client cookbok"
version           "0.1.0"
