---
name: kitchen

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  dokken:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - 'amazonlinux-2'
          - 'centos-7'
          - 'centos-8'
          - 'debian-10'
          - 'debian-9'
          - 'fedora-latest'
          - 'opensuse-leap-15'
          - 'ubuntu-1604'
          - 'ubuntu-1804'
          - 'ubuntu-2004'
        suite:
          - 'cron'
          - 'cron-resource'
          - 'config'
          - 'timer-systemd'
          - 'systemd-timer-resource'
          - 'service-systemd'
      fail-fast: false

    steps:
      - name: Check out cookbook code
        uses: actions/checkout@master
      - name: Install Chef Infra Client
        uses: actionshub/chef-install@main
      - name: Dokken
        uses: actionshub/kitchen-dokken@main
        env:
          CHEF_LICENSE: accept-no-persist
          KITCHEN_LOCAL_YAML: kitchen.dokken.yml
        with:
          suite: ${{ matrix.suite }}
          os: ${{ matrix.os }}
